# Generated by Django 3.2.9 on 2021-12-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halpapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community_resource',
            name='geocoded_column',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community_resource',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='community_resource',
            name='street_address',
            field=models.CharField(max_length=55),
        ),
    ]
