# Generated by Django 3.2.9 on 2021-12-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halpapi', '0002_auto_20211206_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reactions',
            field=models.ManyToManyField(related_name='reactions', through='halpapi.Review_Reaction', to='halpapi.Reaction'),
        ),
    ]
