# Generated by Django 3.2.9 on 2021-12-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halpapi', '0003_review_reactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='community_resource_id',
            new_name='community_resource',
        ),
    ]
