# Generated by Django 3.2.10 on 2021-12-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halpapi', '0004_rename_community_resource_id_review_community_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_reaction',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='halpapi.reviewer'),
        ),
    ]
