# Generated by Django 3.2.10 on 2021-12-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halpapi', '0005_review_reaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_reaction',
            old_name='user',
            new_name='reviewer',
        ),
    ]
