# Generated by Django 3.2.10 on 2021-12-14 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halpapi', '0006_rename_user_review_reaction_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_reaction',
            name='reaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='halpapi.reaction'),
        ),
    ]
