# Generated by Django 3.2.10 on 2021-12-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halpapi', '0007_alter_review_reaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_resource',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
